// src/context/JobsContext.tsx
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { supabase } from "../services/supabase-client";
import { addJob as addJobAPI, updateJob as updateJobAPI, deleteJob as deleteJobAPI } from "../services/api";


interface CompanyData {
  name: string;
  description: string;
  contactEmail: string;
  contactPhone: string;
}


export interface Job {
  id: string;
  title: string;
  type: string;
  location: string;
  description: string;
  salary: string;
  company: CompanyData;
}


// id is omitted since it`s automatically generated by the db
type NewJobReq = Omit<Job, "id">;

/**
 * @interface JobsContextType
 * @description the shape of the data and functions exposed by the Jobs Context.
 */
interface JobsContextType {
  jobs: Job[] | null;

  loading: boolean;

  error: Error | null;
  /** Function to force a fresh fetch of all job listings from the database. */
  refreshJobs: () => Promise<void>;
  addJob: (newJob: NewJobReq) => Promise<void>;
  updateJob: (updatedJob: Job) => Promise<void>;
  deleteJob: (id: string) => Promise<void>;
}


const JobsContext = createContext<JobsContextType | undefined>(undefined);

/**
 * @function JobsProvider
 * @description Provides job data and CRUD functionality to all child components 
 * 
 * It serves as the Single Source of Truth for the job list.
 * 
 * * **Synchronization Strategy:** CRUD functions (add, update, delete) use the API result to
 * **directly manipulate the local 'jobs' state**  instead of
 * requiring a full re-fetch of the list.
 * * @param {object} props - The component props.
 * @param {ReactNode} props.children - The child elements to be wrapped by the provider.
 * @returns {JSX.Element} The JobsContext.Provider component.
 */
export const JobsProvider = ({ children }: { children: ReactNode }): JSX.Element => {
  const [jobs, setJobs] = useState<Job[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  /**
   * @function refreshJobs
   * @description Fetches all job listings from the Supabase API, updates the 'jobs' state,
   * and manages 'loading' and 'error' states. Used for initial load and explicit full refreshes.
   */
  const refreshJobs = async () => {
    try {
      setLoading(true);
     setError(null);
      const { data, error } = await supabase
        .from("jobs")
        .select()
        .order("created_at", { ascending: false }); 
      if (error) throw new Error(error.message);
      setJobs(data as Job[]);
    } catch (err) {
      setError(err as Error);
      setJobs(null);
    } finally {
      setLoading(false);
    }
  };

  // Fetch jobs on initial component mount
  useEffect(() => {
    refreshJobs();
  }, []);

  /**
   * @function addJob
   * @description Submits a new job to the API and prepends the resulting data to the local 'jobs' state.
   * @param {NewJobReq} newJob - The job data to be added.
   */
  const addJob = async (newJob: NewJobReq) => {
    const data = await addJobAPI(newJob);
    // Optimistic/Direct Update: Prepend the new job to the list instantly.
    setJobs((prev) => (prev ? [data, ...prev] : [data]));
  };

  /**
   * @function updateJob
   * @description Submits an updated job to the API and replaces the old version in the local 'jobs' state.
   * @param {Job} updatedJob - The full job object with updated fields.
   */
  const updateJob = async (updatedJob: Job) => {
    const data = await updateJobAPI(updatedJob);
    // Direct Update: Find and replace the job in the list instantly.
    setJobs((prev) =>
     prev ? prev.map((job) => (job.id === data.id ? data : job)) : [data]
    );
  };

  /**
   * @function deleteJob
   * @description Deletes a job from the API and filters it out of the local 'jobs' state.
   * @param {string} id - The ID of the job to delete.
   */
  const deleteJob = async (id: string) => {
    await deleteJobAPI(id);
    // Optimistic/Direct Update: Filter the deleted job out of the list instantly.
    setJobs((prev) => (prev ? prev.filter((job) => job.id !== id) : prev));
  };

  return (
    <JobsContext.Provider
      value={{ jobs, loading, error, refreshJobs, addJob, updateJob, deleteJob }}
    >
      {children}
    </JobsContext.Provider>
  );
};

/**
 * @function useJobs
 * @description A custom hook that consumes the Jobs Context, providing access to
 * the job data, loading state, error state, and CRUD action functions.
 * @returns {JobsContextType} The context value (jobs, loading, error, refreshJobs, addJob, updateJob, deleteJob).
 * @throws {Error} If used outside of a JobsProvider.
 */
export const useJobs = (): JobsContextType => {
  const context = useContext(JobsContext);
  if (!context) throw new Error("useJobs must be used within a JobsProvider");
  return context;
};